openapi: 3.0.1
info:
  title: Kayak_food_delivery_and_reservation_booking
  version: "1"
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /menu:
    get:
      summary: get food menu of given restaurant
      description: Pass the restaurant name as a header and resource will return menu.
      parameters: []
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /oder:
    post:
      parameters: []
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /delivery/address:
    post:
      parameters: []
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /reservations/location:
    post:
      parameters: []
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /feedback:
    post:
      summary: live details of the match
      description: Fixtures and related endpoint. Live details
      parameters: []
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
x-wso2-application-security:
  security-types:
   - oauth2
  optional: false
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - https://localhost:9443/am/sample/pizzashack/v1/api/
  type: http
  securityConfig:
    type: basic
    username: user
x-wso2-sandbox-endpoints:
  urls:
   - https://localhost:9443/am/sample/pizzashack/v1/api/
  type: http
  securityConfig:
    type: basic
    username: user
x-wso2-basePath: /food/1
x-wso2-transports:
  - http
  - https
